name: Build Report
on:
  push:
    paths:
      - '**/report.tex'
jobs:
  test:
    runs-on: ubuntu-latest
    container: blang/latex:ctanfull
    steps:
      - uses: actions/checkout@v2
      - name: Runs Tests
        run: cd doc && latexmk -pdf report.tex
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: 'doc/*.pdf'
