name: tests
on:
  push:
    paths:
      - '**.c'
      - '**.h'
jobs:
  test:
    runs-on: ubuntu-latest
    container: gcc:10
    steps:
      - uses: actions/checkout@v2
      - name: Runs Tests
        run: make all